# Generated by Django 5.1.6 on 2025-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_slip",
            field=models.ImageField(blank=True, null=True, upload_to="payment_slips/"),
        ),
    ]
