# Generated by Django 5.1.6 on 2025-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='waiting_payment', max_length=50),
        ),
    ]
