# Generated by Django 5.1.6 on 2025-03-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='waiting_confirm', max_length=50),
        ),
    ]
