# Generated by Django 5.1.6 on 2025-03-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_shipping_address_order_address_line_and_more'),
        ('user', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='user.address'),
        ),
    ]
