# Generated by Django 5.1.6 on 2025-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_cart_selected_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
